import numpy as np


def gaussPDF(Data, Mu, Sigma):
    """
    Likelihood of datapoint(s) to be generated by a Gaussian parameterized by center and covariance.

    :param Data:  D x N array representing N datapoints of D dimensions.
    :param Mu:    D x 1 vector representing the center of the Gaussian.
    :param Sigma: D x D array representing the covariance matrix of the Gaussian.

    :return:      1 x N vector representing the likelihood of the N datapoints.
    """
    nbVar, nbData = Data.shape
    Data = Data.T - Mu.T
    prob = np.sum(np.dot(Data, np.linalg.inv(Sigma)) * Data, axis=1, keepdims=True)
    prob = np.exp(-0.5*prob) / np.sqrt((2*np.pi)**nbVar * np.abs(np.linalg.det(Sigma)) + np.finfo(float).tiny)
    return prob
